### ISSUE TITLE
Add support for Databricks

### ISSUE THREAD

**Issue by jaredpavan** [ddasutein/AutoRename#26]
When downloading results files from Databricks it always uses the file name `export.csv`, so my Downloads folder is often littered with files like `export (46).csv`. Add support for `cloud.databricks.com`! I can make the changes and submit the pull request if you wish.

**Comment by ddasutein** [comment]
Hello!

I would love to add support for that website but it is not something most users will access. In the future, I am planning to add support websites apart from Twitter, LINE, and Reddit. In this case, if this is an internal company website then you are more than welcome to fork the repository and modify it to your meet your requirements. Kindly use the `master` branch as your base and not `dev` branch.
